import type { Metadata } from "next";
import "./globals.css";
import DefaultLayout from "@/components/DefaultLayout";

export const metadata: Metadata = {
  title: "Gemiverse global",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
